#ifndef MLIR_DIALECT_LLHD_LLHDOPS_H
#define MLIR_DIALECT_LLHD_LLHDOPS_H

#include "Dialect/LLHD/LLHDDialect.h"
#include "mlir/IR/StandardTypes.h"
#include "mlir/Interfaces/ControlFlowInterfaces.h"
#include "mlir/Interfaces/SideEffects.h"

namespace mlir {
namespace llhd {

/// Retrieve the class declarations generated by TableGen
#define GET_OP_CLASSES
#include "Dialect/LLHD/LLHDOps.h.inc"

} // namespace llhd
} // namespace mlir

#endif // MLIR_DIALECT_LLHD_LLHDOPS_H
